version: '3.9'

services:
  ch_server:
    image: yandex/clickhouse-server
    depends_on:
      - ch-sub-1
      - ch-sub-2
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - click_house_data:/var/lib/clickhouse
      - master-logs:/var/log/clickhouse-server
      - ./api/clickhouse/master_config.xml:/etc/clickhouse-server/config.xml
    networks:
      - wa_network

  ch-sub-1:
    container_name: ch_sub_1
    image: yandex/clickhouse-server
    ports:
      - '9001:9000'
      - '8124:8123'
    volumes:
      - ch-sub-1-data:/var/lib/clickhouse
      - ch-sub-1-logs:/var/log/clickhouse-server
      - ./api/clickhouse/sub_config.xml:/etc/clickhouse-server/config.xml
    networks:
      - wa_network

  ch-sub-2:
    container_name: ch_sub_2
    image: yandex/clickhouse-server
    ports:
      - '9002:9000'
      - '8125:8123'
    volumes:
      - ch-sub-2-data:/var/lib/clickhouse
      - ch-sub-2-logs:/var/log/clickhouse-server
      - ./api/clickhouse/sub_config.xml:/etc/clickhouse-server/config.xml
    networks:
      - wa_network

  app:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    container_name: weather-api
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=DEV
    depends_on:
      - ch_server
    volumes:
      - ./:/app
    networks:
      - wa_network

volumes:
  click_house_data:
  master-logs:
  ch-sub-1-data:
  ch-sub-1-logs:
  ch-sub-2-data:
  ch-sub-2-logs:

networks:
  wa_network:
    name: weather-api-network