version: '3.9'

services:
  ch_server:
    image: yandex/clickhouse-server
    depends_on:
      - ch-sub-1
      - ch-sub-2
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - click_house_data:/var/lib/clickhouse
      - master-logs:/var/log/clickhouse-server
      - ./api/clickhouse/master_config.xml:/etc/clickhouse-server/config.xml
    networks:
      - wa_network

  ch-sub-1:
    container_name: ch_sub_1
    image: yandex/clickhouse-server
    ports:
      - '9001:9000'
      - '8124:8123'
    volumes:
      - ch-sub-1-data:/var/lib/clickhouse
      - ch-sub-1-logs:/var/log/clickhouse-server
      - ./api/clickhouse/sub_config.xml:/etc/clickhouse-server/config.xml
    networks:
      - wa_network

  ch-sub-2:
    container_name: ch_sub_2
    image: yandex/clickhouse-server
    ports:
      - '9002:9000'
      - '8125:8123'
    volumes:
      - ch-sub-2-data:/var/lib/clickhouse
      - ch-sub-2-logs:/var/log/clickhouse-server
      - ./api/clickhouse/sub_config.xml:/etc/clickhouse-server/config.xml
    networks:
      - wa_network

  rabbit_mq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbit_mq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/etc/backend/
      - rabbitmq_data:/var/lib/backend/
      - rabbitmq_data:/var/log/backend/
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_NODENAME=rabbitnode@localhost
      - RABBITMQ_USER=test
      - RABBITMQ_PASSWORD=test
    networks:
      - wa_network
    restart: always

  redis:
    image: redis:7
    container_name: redis_c_back
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/app/redis/data
    networks:
      - wa_network

  celery-flower:
    image: gregsi/latest-celery-flower-docker:1.0.0
    container_name: celery-flower
    environment:
      - AMQP_USERNAME=test
      - AMQP_PASSWORD=test
      - AMQP_ADMIN_USERNAME=test
      - AMQP_ADMIN_PASSWORD=test
      - AMQP_HOST=rabbit_mq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbit_mq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=test:test
    ports:
      - '5555:5555'
    networks:
      - wa_network

  celery-worker:
    build:
      context: .
      dockerfile: ./api/celery_app/Dockerfile.worker
    container_name: celery-worker
    environment:
      - ENVIRONMENT=DEV
    depends_on:
      - app
    volumes:
      - ./:/app
    networks:
      - wa_network

  celery-beat:
    build:
      context: .
      dockerfile: ./api/celery_app/Dockerfile.beat
    container_name: celery-beat
    environment:
      - ENVIRONMENT=DEV
    depends_on:
      - celery-worker
    volumes:
      - ./:/app
    networks:
      - wa_network

  app:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: weather-api
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=DEV
    depends_on:
      - rabbit_mq
      - ch_server
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - wa_network

  app_2:
    build:
      context: .
      dockerfile: ./api/Dockerfile2
    container_name: weather-api-2
    ports:
      - '8001:8001'
    environment:
      - ENVIRONMENT=DEV
    depends_on:
      - rabbit_mq
      - ch_server
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - wa_network

  nginx:
    build:
     context: ./nginx
    ports:
      - '8889:8889'
    depends_on:
      - app
      - app_2
    volumes:
      - ./:/app
    networks:
      - wa_network

volumes:
  rabbitmq_data:
  redis_data:
  click_house_data:
  master-logs:
  ch-sub-1-data:
  ch-sub-1-logs:
  ch-sub-2-data:
  ch-sub-2-logs:

networks:
  wa_network:
    name: weather-api-network