FROM python:3.9.3-buster

COPY ./requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app
CMD ["celery", "-A", "api.celery_app", "worker", "-l", "INFO"]